#!/usr/bin/env bash
# shellcheck disable=SC2154
#configures a new Ubuntu machine to be identical to another server, runnig nginx

sudo apt-get update && sudo apt-get install nginx -y

sudo chown -R "$USER":"$USER" /var/www/html/index.nginx-debian.html
sudo chown -R "$USER":"$USER" /etc/nginx/sites-available/default
sudo chown -R "$USER":"$USER" /var/www/html

echo "Hello World!" > /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" > /var/www/html/404.html

NotFound=\
"server {
	listen 80 default_server;
	listen [::]:80 default_server;
	root /var/www/html;
	index index.html index.htm index.nginx-debian.html;
	server_name _;
	location /redirect_me {
		return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
	}
 	error_page 404 /404.html;
    	location /404 {
      		root /var/www/html;
      		internal;
    	}
}"

echo -e "$NotFound" > /etc/nginx/sites-available/default

custom_header="http {\\n\\tadd_header X-Served-By \"$HOSTNAME\";"
sudo sed -i "s/http {/$custom_header/" /etc/nginx/nginx.conf

sudo service nginx restart
