#!/usr/bin/env bash
#Script is instaling and configuring HAproxy on my loadbalancing(lb-01) server.
sudo apt-get update
sudo apt install -y software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy
sudo apt-get update
sudo apt-get install haproxy
sudo mv /etc/haproxy/haproxy.cfg{,.original}
sudo touch /etc/haproxy/haproxy.cfg

echo "defaults
	log	global
	option	httplog
frontend web-server
	bind *:80
	mode    http
	default_backend web-servers
	
backend web-servers
	balance	roundrobin
	server 13540-web-01 52.86.242.93:80 check
	server 13540-web-02 35.174.208.155:80 check" >> /etc/haproxy/haproxy.cfg

#Enable haproxy to be managed via init script
systemctl enable haproxy

#start haproxy
systemctl start haproxy
