#!/usr/bin/env bash
# Installs and configures HAproxy on webserver 3, distributes requests
# using a roundrobin algorithm
 
sudo apt-get update
sudo apt-get upgrade
 
sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy
sudo apt-get -y update
 
sudo apt-get -y install haproxy
 
balancer="\
frontend web-frontend
    bind *:80
    mode http
    default_backend web-backend
 
backend web-backend
    balance roundrobin
    server 13540-web-01 54.226.29.105 check
    server 13540-web-02 54.236.52.173 check
"
echo "$balancer" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart